[package]
name = "mp4_to_m3u8"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
walkdir = "2.5"
indicatif = "0.17"
tokio = { version = "1.0", features = ["process", "rt-multi-thread", "macros", "time"] }
ffmpeg-sidecar = "2.0.6"
regex = "1.10"
