[package]
name = "maya"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
clear_node_modules = { workspace = true }
clear_lock = { workspace = true } 