[package]
name = "maya-media"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Maya 图片压缩与视频转换能力"

[dependencies]
maya-core = { workspace = true }
maya-fs = { workspace = true }
ffmpeg-sidecar = { version = "2.0.6", default-features = false }
image = "0.25.6"
oxipng = "9.1.5"
rayon = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tempfile = { workspace = true }
