[package]
name = "maya-fs"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Maya 文件扫描、清理、归档与原子 I/O 能力"

[dependencies]
maya-core = { workspace = true }
ignore = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true }
