[package]
name = "maya-fs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Maya 文件扫描、清理、归档与原子 I/O 能力"

[dependencies]
maya-core = { workspace = true }
ignore = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true }
