[package]
name = "compress_pictures"
version = "0.1.0"
edition = "2021"

[dependencies]
oxipng = "9.1.5"
walkdir = { workspace = true }
image = "0.25.6"
anyhow = "1.0.98"
maya_common = { path = "../maya_common" }
