[package]
name = "clear_lock"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3", features = ["console"] }

[dev-dependencies]
tempfile = "3.5.0"
